name: PR-TestCoverage-Report
on: [ pull_request ] # ê¹ƒ ì €ì¥ì†Œì˜ push, pull_request ì´ë²¤íŠ¸ì— ì˜í•´ íŠ¸ë¦¬ê±°ëœë‹¤.
jobs:
  reporting:
    runs-on: ubuntu-latest # ì›Œí¬í”Œë¡œìš°ì˜ ì´ë¦„
    steps:
      - uses: madrapps/jacoco-report@v1.2
        with:
          title: ğŸ“ í…ŒìŠ¤íŠ¸ ì»¤ë²„ë¦¬ì§€ ë¦¬í¬íŠ¸ì…ë‹ˆë‹¤
          paths: ${{ github.workspace }}/backend/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 50
          min-coverage-changed-files: 50